### PR TITLE
Fixes #39 - Support for hierarchical categories.

### LINKED ISSUE #39: Category picker not working in MW 1.24.1
We installed the editor to a new MW installation 1.24.1 (only the database was upgraded from 1.17.0). The MW language is set to French. The editor version is "1.5.6_0 [B551+04.01.2015], CKEditor 4.4.5 [revision 25cdcad]". The editor works fine except for the category picker. 

Here's the behavior we have:
1. No category is loaded in the list when the picker loads
2. If we enter " " (a space) in the textbox all the categories are then loaded into the list (without indent to simulate the hierarchy of the categories)
3. When typing an existing category name we get the "no category found" message
4. If I select a category from the list, its name is tranfered to the textbox, but the message "Not found, the category is new" (in French) is shown and the listbox is emptied. However, if I click the OK button the category is added to the page.

We tested the editor with MW 1.24.1 under both Apache and IIS. We also tested with IE, Chrome and FF. We always get the same behavior.

Is this an issue other people can reproduce? Any help would be appreciated.

image
image

### PR DESCRIPTION
**Pull request by DavidBeaumier**
Added the support for hierarchies in categories. 
- Search now finds a category regardless of its hierarchical index.
- Categories are displayed in a "pseudo-hierarchical" manner.
- All categories already associated with the page are automatically shown in the dialog
- It's possible to create multiple new categories in a single operation by clicking on the "Ajouter" (add) button.

categorydialog-hierarchicalsupport

However, we did not localize all the strings. You will find some French labels. I appologize for that.

### CODE REVIEW

**Comment by riparap** [comment]
I have used SourceTree to Access github. I am not github expert... do you know if it is somehow possible to create new  branch here and then merge your modification into it leave branch Ckeditor_v4 untouched until everyhing is fixed with new dialog?  .... Or should I clone your copy of wysiwyg and provide f.ex translations first to you using your clone?

**Comment by DavidBeaumier** [comment]
Let me check if it's possible to merge to a child branch. Anyway, I think you should wait for my next commit before you do any integration.

**Comment by DavidBeaumier** [comment]
To integrate to a child branch I think you'll have to create this branch before it submit another pull request. Here's how I suggest we do it:
1. You create a branch from Mediawiki-wysiwyg:CKeditor_v4
2. You close this pull reqest
3. I commit new stuff to my fork
4. I submit a new pull request by targeting the newly created branch 

Sounds good to you?

**Comment by riparap** [comment]
I created a new branch with name "CKeditor_V4_Category" and as you suggested closed this one.

**Pull request closed without merging**
